version: "3"

services:
  redis-db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: ["--save", "1", "1"]
  api:
    image: williamzhang0306/metro_bike_app:dev
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    entrypoint: python3 api.py
    environment:
      - LOG_LEVEL=INFO
      - REDIS_IP=redis-db
  worker:
    image: williamzhang0306/metro_bike_app:dev
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    entrypoint: python3 worker.py
    environment:
      - LOG_LEVEL=INFO
      - REDIS_IP=redis-db