version: "3"

services:
  redis-db:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    command: ["--save", "1", "1"]
  api:
    image: api
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - redis-db
    entrypoint: python3 api.py
    environment:
      - LOG_LEVEL=INFO
      - REDIS_IP=redis-db
  # worker:
  #   image: worker
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - redis-db
  #   entrypoint: python3 worker.py
  #   environment:
  #     - LOG_LEVEL=INFO
  #     - REDIS_IP=redis-db